import * as React from "react";
import * as AccordionPrimitive from "@radix-ui/react-accordion";
import { cn } from "../../lib/cn";

/**
 * Accordion — Radix-backed collapsible-section list. Use for FAQ-style
 * disclosures, long forms split into expandable sections, settings
 * pages with grouped subsections, and "review your details" screens
 * where the user wants to drill into specific groups.
 *
 *   <Accordion type="single" collapsible defaultValue="basic">
 *     <AccordionItem value="basic">
 *       <AccordionTrigger>Basic info</AccordionTrigger>
 *       <AccordionContent>…</AccordionContent>
 *     </AccordionItem>
 *     <AccordionItem value="address">
 *       <AccordionTrigger>Address</AccordionTrigger>
 *       <AccordionContent>…</AccordionContent>
 *     </AccordionItem>
 *   </Accordion>
 *
 * `type="single" collapsible` allows one section open at a time +
 * collapsing the active one. `type="multiple"` lets several be open
 * simultaneously (good for forms where the user might want context
 * from multiple sections at once).
 *
 * Animations use Radix's `data-state` attributes; the keyframes live
 * in tokens.css via the `accordion-down` / `accordion-up` utility
 * classes generated by UnoCSS at runtime.
 */

const Accordion = AccordionPrimitive.Root;

const AccordionItem = React.forwardRef<
  React.ElementRef<typeof AccordionPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Item>
>(({ className, ...props }, ref) => (
  <AccordionPrimitive.Item
    ref={ref}
    className={cn("border-b border-zen-border last:border-b-0", className)}
    {...props}
  />
));
AccordionItem.displayName = "AccordionItem";

const AccordionTrigger = React.forwardRef<
  React.ElementRef<typeof AccordionPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Trigger>
>(({ className, children, ...props }, ref) => (
  <AccordionPrimitive.Header className="flex">
    <AccordionPrimitive.Trigger
      ref={ref}
      className={cn(
        "flex flex-1 items-center justify-between gap-2",
        "py-3 px-1 text-sm font-medium text-left",
        "bg-transparent border-0 cursor-pointer",
        "transition-colors hover:text-zen-foreground",
        "text-zen-foreground",
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zen-ring focus-visible:ring-inset rounded-zen-sm",
        /* Rotate the trailing chevron when open via data-state. */
        "[&[data-state=open]>svg.zen-acc-chevron]:rotate-180",
        className,
      )}
      {...props}
    >
      {children}
      <svg
        className="zen-acc-chevron transition-transform duration-200 text-zen-muted-fg flex-shrink-0"
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden
      >
        <polyline points="6 9 12 15 18 9" />
      </svg>
    </AccordionPrimitive.Trigger>
  </AccordionPrimitive.Header>
));
AccordionTrigger.displayName = AccordionPrimitive.Trigger.displayName;

const AccordionContent = React.forwardRef<
  React.ElementRef<typeof AccordionPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Content>
>(({ className, children, ...props }, ref) => (
  <AccordionPrimitive.Content
    ref={ref}
    /* Radix sets --radix-accordion-content-height; we use it via the
     * `accordion-down` / `accordion-up` keyframes below. */
    className={cn(
      "overflow-hidden text-sm",
      "data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down",
    )}
    {...props}
  >
    <div className={cn("pb-3 px-1 pt-0 text-zen-foreground", className)}>
      {children}
    </div>
  </AccordionPrimitive.Content>
));
AccordionContent.displayName = AccordionPrimitive.Content.displayName;

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent };
