import * as React from "react";
import * as AccordionPrimitive from "@radix-ui/react-accordion";
import { cn } from "../../lib/cn";

/**
 * Accordion — Radix-backed collapsible-section list. Use for FAQ-style
 * disclosures, long forms split into expandable sections, settings
 * pages with grouped subsections, and "review your details" screens
 * where the user wants to drill into specific groups.
 *
 *   <Accordion type="single" collapsible defaultValue="basic">
 *     <AccordionItem value="basic">
 *       <AccordionTrigger>Basic info</AccordionTrigger>
 *       <AccordionContent>…</AccordionContent>
 *     </AccordionItem>
 *     <AccordionItem value="address">
 *       <AccordionTrigger>Address</AccordionTrigger>
 *       <AccordionContent>…</AccordionContent>
 *     </AccordionItem>
 *   </Accordion>
 *
 * `type="single" collapsible` allows one section open at a time +
 * collapsing the active one. `type="multiple"` lets several be open
 * simultaneously (good for forms where the user might want context
 * from multiple sections at once).
 *
 * Animations use Radix's `data-state` attributes; the keyframes live
 * in tokens.css via the `accordion-down` / `accordion-up` utility
 * classes generated by UnoCSS at runtime.
 */

const Accordion = AccordionPrimitive.Root;

const AccordionItem = React.forwardRef<
  React.ElementRef<typeof AccordionPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Item>
>(({ className, ...props }, ref) => (
  <AccordionPrimitive.Item
    ref={ref}
    className={cn("zen-border-b zen-border-zen-border last:zen-border-b-0", className)}
    {...props}
  />
));
AccordionItem.displayName = "AccordionItem";

const AccordionTrigger = React.forwardRef<
  React.ElementRef<typeof AccordionPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Trigger>
>(({ className, children, ...props }, ref) => (
  <AccordionPrimitive.Header className="zen-flex">
    <AccordionPrimitive.Trigger
      ref={ref}
      className={cn(
        "zen-flex zen-flex-1 zen-items-center zen-justify-between zen-gap-2",
        "zen-py-3 zen-px-1 zen-text-sm zen-font-medium zen-text-start",
        "zen-bg-transparent zen-border-0 zen-cursor-pointer",
        "zen-transition-colors hover:zen-text-zen-foreground",
        "zen-text-zen-foreground",
        "focus-visible:zen-outline-none focus-visible:zen-ring-2 focus-visible:zen-ring-zen-ring focus-visible:zen-ring-inset zen-rounded-zen-sm",
        /* Rotate the trailing chevron when open via data-state. */
        "[&[data-state=open]>svg.zen-acc-chevron]:zen-rotate-180",
        className,
      )}
      {...props}
    >
      {children}
      <svg
        className="zen-acc-chevron zen-transition-transform zen-duration-200 zen-text-zen-muted-fg zen-flex-shrink-0"
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden
      >
        <polyline points="6 9 12 15 18 9" />
      </svg>
    </AccordionPrimitive.Trigger>
  </AccordionPrimitive.Header>
));
AccordionTrigger.displayName = AccordionPrimitive.Trigger.displayName;

const AccordionContent = React.forwardRef<
  React.ElementRef<typeof AccordionPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Content>
>(({ className, children, style, ...props }, ref) => (
  <AccordionPrimitive.Content
    ref={ref}
    /* core's keyframes interpolate height to --zen-collapsible-content-height, a
     * neutral name — core is shared with bindings that are not on Radix, and it
     * used to read Radix's name directly. Radix publishes the measurement under
     * its own name; this is the mapping. `style` spreads after, so a caller can
     * still override. */
    style={
      {
        "--zen-collapsible-content-height": "var(--radix-accordion-content-height)",
        ...style,
      } as React.CSSProperties
    }
    className={cn(
      "zen-overflow-hidden zen-text-sm",
      "data-[state=closed]:zen-anim-accordion-up data-[state=open]:zen-anim-accordion-down",
    )}
    {...props}
  >
    <div className={cn("zen-pb-3 zen-px-1 zen-pt-0 zen-text-zen-foreground", className)}>
      {children}
    </div>
  </AccordionPrimitive.Content>
));
AccordionContent.displayName = AccordionPrimitive.Content.displayName;

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent };
