import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import UnoCSS from "unocss/vite";
import { resolve } from "path";

export default defineConfig({
  plugins: [
    react(),
    UnoCSS({
      // Configure UnoCSS for library build
      // This will generate CSS from utility classes used in components
    }),
  ],
  css: {
    modules: {
      // Generate scoped class names for CSS modules
      // This ensures consistent class name generation
      generateScopedName: "[local]___[hash:base64:5]",
      // Ensure CSS modules are properly handled
      localsConvention: "camelCase",
    },
  },
  build: {
    // Don't empty dist directory to preserve .d.ts files generated by tsc
    emptyOutDir: false,
    lib: {
      entry: resolve(__dirname, "src/index.ts"),
      name: "JetstreamComponents",
      formats: ["es"],
      fileName: "index",
    },
    rollupOptions: {
      // Externalize dependencies that should not be bundled
      external: [
        "react",
        "react-dom",
        "react/jsx-runtime",
        // Note: react-router-dom is used in dropdown component
        // It's bundled here to avoid requiring consumers to install it
        // If you prefer to externalize it, consumers using dropdown must have it installed
        // Optional peer deps — lazy-loaded by Chart/RichText/Map/Camera. Never
        // bundled; consumers install them only if they use those components.
        "recharts",
        "jodit-pro-react",
        "leaflet",
        "react-leaflet",
        "react-webcam",
      ],
      output: {
        // Provide global variable names for UMD builds (not used for ESM, but good to have)
        globals: {
          react: "React",
          "react-dom": "ReactDOM",
          "react-router-dom": "ReactRouterDOM",
        },
        // Emit one file per module instead of a single bundle. This is half of
        // what makes the library tree-shakeable; the other half is
        // `sideEffects` in package.json, and NEITHER WORKS ALONE:
        //
        //   - Bundled into one module, `sideEffects: false` is all-or-nothing —
        //     the blob is used (you imported Button), so none of it can go.
        //   - Split into modules but without `sideEffects`, rollup must assume
        //     every module might do something on import, and keeps them all.
        //
        // Together they took a single <Button> from 151 kB gzipped to 17 kB.
        // The comment here used to claim `false` was "for better tree-shaking",
        // which was backwards: it was the thing preventing it. Measured with
        // scripts/check-bundle-size.mjs — run it before changing this.
        preserveModules: true,
        preserveModulesRoot: "src",
        // Ensure CSS file is named style.css to match package.json exports
        assetFileNames: (assetInfo) => {
          // Rename the CSS file to style.css
          if (assetInfo.name && assetInfo.name.endsWith(".css")) {
            return "style.css";
          }
          // Keep other assets with their original names
          return assetInfo.name || "[name].[ext]";
        },
      },
    },
    // Bundle all CSS into one file for easier consumption
    cssCodeSplit: false,
    outDir: "dist",
    // Generate source maps for debugging
    sourcemap: true,
    // Minify the output
    minify: "esbuild",
  },
});
